[manifest]
version = "1.0.0"
priority = 0

[[patches]]
[patches.pattern]
target = "main.lua"
position = "after"
times = 1
pattern = "local os = love.system.getOS()"
payload = "love.window.setMode(2, 1, {highdpi = (os == 'OS X' or os == 'iOS' or os == 'Android')})"
match_indent = true
